version: 1
update_configs:
  - package_manager: "submodules"
    directory: "./"
    update_schedule: "daily"
    allowed_updates:
      - match:
          dependency_name: "2-MansurSakiev"
      - match:
          dependency_name: "2-Lev0nid"
      - match:
          dependency_name: "2-kettlberry"
      - match:
          dependency_name: "2-IraSheremet"
      - match:
          dependency_name: "2-IlyaMuravjov"
      - match:
          dependency_name: "2-IAmFunkyFrog"
      - match:
          dependency_name: "2-GalbadrakhB"
      - match:
          dependency_name: "2-foreverjun"
      - match:
          dependency_name: "2-esvault"
      - match:
          dependency_name: "2-depressedwizard"
      - match:
          dependency_name: "2-DelRoso"
      - match:
          dependency_name: "2-danielsheh02"
      - match:
          dependency_name: "2-baranov1dragonsuper"
      - match:
          dependency_name: "2-AzimMuradov"
      - match:
          dependency_name: "2-AShlegel"
      - match:
          dependency_name: "2-artmotika"
      - match:
          dependency_name: "2-AndreyBryns"
    ignored_updates:
      - match:
          dependency_name: "2-grading-tests"
