version: 1
update_configs:
  - package_manager: "submodules"
    directory: "./"
    update_schedule: "daily"
    allowed_updates:
      - match:
          dependency_name: "2-AlexanderRunov"
      - match:
          dependency_name: "2-zishkaz"
      - match:
          dependency_name: "2-XeniaKart"
      - match:
          dependency_name: "2-ViktorKarasss"
      - match:
          dependency_name: "2-ToTTopBYxe"
      - match:
          dependency_name: "2-Tizain"
      - match:
          dependency_name: "2-TimPushkin"
      - match:
          dependency_name: "2-TheDarkRisen"
      - match:
          dependency_name: "2-st085683"
      - match:
          dependency_name: "2-SofuriHafe"
      - match:
          dependency_name: "2-smmac72"
      - match:
          dependency_name: "2-SlavaLatokhin"
      - match:
          dependency_name: "2-ShishaK1N9"
      - match:
          dependency_name: "2-rudolf101"
      - match:
          dependency_name: "2-Ramazanov-Amir"
      - match:
          dependency_name: "2-qsqnk"
      - match:
          dependency_name: "2-PyRayman"
      - match:
          dependency_name: "2-pervomai"
      - match:
          dependency_name: "2-Naniduan"
      - match:
          dependency_name: "2-Mishavint"
      - match:
          dependency_name: "2-michael555444"
      - match:
          dependency_name: "2-MDubovik"
      - match:
          dependency_name: "2-MashrurIslam"
      - match:
          dependency_name: "2-maria-atmazhitova"
      - match:
          dependency_name: "2-MansurSakiev"
      - match:
          dependency_name: "2-Lev0nid"
      - match:
          dependency_name: "2-kettlberry"
      - match:
          dependency_name: "2-IraSheremet"
      - match:
          dependency_name: "2-IlyaMuravjov"
      - match:
          dependency_name: "2-IAmFunkyFrog"
      - match:
          dependency_name: "2-GalbadrakhB"
      - match:
          dependency_name: "2-foreverjun"
      - match:
          dependency_name: "2-esvault"
      - match:
          dependency_name: "2-depressedwizard"
      - match:
          dependency_name: "2-DelRoso"
      - match:
          dependency_name: "2-danielsheh02"
      - match:
          dependency_name: "2-baranov1dragonsuper"
      - match:
          dependency_name: "2-AzimMuradov"
      - match:
          dependency_name: "2-AShlegel"
      - match:
          dependency_name: "2-artmotika"
      - match:
          dependency_name: "2-AndreyBryns"
    ignored_updates:
      - match:
          dependency_name: "2-grading-tests"
